name: Publish package

on:
  workflow_call:
    inputs:
      publish_gh:
        description: 'Publish package to github'
        default: true
        type: boolean
      publish_pubdev:
        description: 'Publish package to pub.dev'
        default: true
        type: boolean
      melos_params:
        description: 'Melos publish params'
        default: ''
        type: string

jobs:
  publish_gh:
    if: inputs.publish_gh
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2

  publish_pubdev:
    if: inputs.publish_pubdev
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v3

      - name: Dry-run publish to pub.dev
        run: melos publish -y --dry-run ${{ inputs.melos_params }}
      - name: Publish to pub.dev
        run: melos publish -y --no-dry-run ${{ inputs.melos_params }}
