name: Run melos command

on:
  workflow_call:
    inputs:
      command:
        description: 'Melos command name'
        default: 'build_and_test'
        type: string
      runner:
        description: 'Job runner'
        default: 'ubuntu-latest'
        type: string
      env_vars:
        description: List of environment variables to set up, given in env=value format.
        required: false
        type: string

jobs:
  run_command:
    env:
      SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v2

      - name: Set environment variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done

      - name: Run melos command
        run: melos run ${{ inputs.command }}
