name: Push merged version tag

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  version_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: yaml_data
        uses: jbutcher5/read-yaml@main
        with:
          file: './pubspec.yaml'
          key-path: '["version"]'

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.token }}
          custom_tag: ${{ steps.yaml_data.outputs.data }}
